# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a962b269790bfe94110b7369280da6982466d519d1d6832edd0d7fbcb05ef72302edda36a267898ca9993f9abf9a624d79ba8ff61b3229230284d03ab9059e5

test:
  secret_key_base: 96587d671ec506cf48bd4ee8485980cf8cd2c6d9ba1d3978667ca54027f819c8e7ce2ee71b3b808a7a52f0965c7eaa0958a89d86d722b3e290d67a6e33202151

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
